### ISSUE TITLE
Terraform import block

### ISSUE THREAD

**Issue by kimllee** [mongodb/terraform-provider-mongodbatlas#2550] opened 2024-09-03 17:21 UTC
Hello,

Looks like the "new" import block (from Terraform 1.5) doesn't work with importing mongodbatlas_cluster on Atlas.
Only the old way looks fine.
I have tried both but only the CLI import mode (terraform import <target_declared_resource_name> <source_resource_id>) works

What's happening please ?

Thanks.

**Comment by kimllee** [comment] 2024-09-04 07:19
![2024-08-12_11-12](https://github.com/user-attachments/assets/71c023c1-aefd-4f46-a1fb-256c7b07f8f4)

**Comment by oarbusi** [comment] 2024-09-04 14:54
Hi @kimllee ,
Thanks for opening the issue.
To be able to reproduce the issue, we would need more details. Could you specify exactly what is the "old way" of importing that is not working anymore so that we can reproduce the issue? Also, the terraform version and terraform provider version you are using along with the terraform configuration would be helpful. 

Thanks again

**Comment by kimllee** [comment] 2024-09-09 06:33
Hi @oarbusi,

the old way is : 
`terraform import <resource_id_target> <atlas_project_id>-<cluster_name>`

https://developer.hashicorp.com/terraform/cli/import

The new way is : 

`import {
  to = mongodbatlas_cluster.<name>
  id = <existing_cluster_id_on_mongo_atlas>
}
`

https://developer.hashicorp.com/terraform/language/import

It allows to import in bulk mode. For now we are obliged to use the CLI terraform import command for each cluster.
We also have peering to import and other resources...

Is it clearer ?

Thank you :)

**Comment by oarbusi** [comment] 2024-09-09 07:25
Thanks for the extra details @kimllee, now it's clearer.
Could you also provide which version of the terraform provider are you using along with the terraform CLI version?

**Comment by kimllee** [comment] 2024-09-09 12:02
We are using the version 1.8. We have tried with the version 1.18 with no success.
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster
![image](https://github.com/user-attachments/assets/cf55790e-e179-4704-ae85-fa5cd692e599)

**Comment by kimllee** [comment] 2024-09-09 12:19
For example in the documentation of mysql gcp, there's a note about the Terraform's import block

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance

**Comment by EspenAlbert** [comment] 2024-09-16 16:55
Hi @kimllee 
Can you share the configuration? I was able to use the import block:
```terraform
import {
  id = "664619d870c247237f4b86a6-atlas-init"
  to = mongodbatlas_cluster.project_cluster
}
```
in my case: 
- `664619d870c247237f4b86a6` is the `project_id`
- `atlas-init` is the cluster name

*Update: From your configuration it looks like you use the `existing_cluster_id_on_mongo_atlas` instead of `{project_id}-{cluster_name}`

**Comment by kimllee** [comment] 2024-09-17 12:06
> Hi @kimllee Can you share the configuration? I was able to use the import block:
> 
> ```hcl
> import {
>   id = "664619d870c247237f4b86a6-atlas-init"
>   to = mongodbatlas_cluster.project_cluster
> }
> ```
> 
> in my case:
> 
>     * `664619d870c247237f4b86a6` is the `project_id`
> 
>     * `atlas-init` is the cluster name
> 
> 
> *Update: From your configuration it looks like you use the `existing_cluster_id_on_mongo_atlas` instead of `{project_id}-{cluster_name}`

Hello, 

Interesting ! Will try soon. I guess it should be documented :)

**Comment by EspenAlbert** [comment] 2024-09-20 12:07
Hi again @kimllee 
I'll close this issue as this is a bigger feature request (since we will want to update all resources with the import block). 
I have created an internal ticket to track that progress.
(if you still have issues importing your cluster, feel free to re-open 👍)

**Closed as completed by EspenAlbert** 2024-09-20 12:07 UTC

**Comment by kimllee** [comment] 2024-10-03 17:24
> Hi again @kimllee I'll close this issue as this is a bigger feature request (since we will want to update all resources with the import block). I have created an internal ticket to track that progress. (if you still have issues importing your cluster, feel free to re-open 👍)

Hi @EspenAlbert it's working fine !
Thanks a lot :)
