### ISSUE TITLE
Adding IP to access List failed when lot of entries

### ISSUE THREAD

**Issue by srenno** [mongodb/terraform-provider-mongodbatlas#470] opened 2021-06-03 13:16 UTC
Hi everyone, 

I use terraform with azure provider and mongodbatlas provider in order to add azure outbound IP in Atlas IP Access List.

> I don't use peering VPC and private link because some azure services are not in private VPC and some Atlas environement are in shared tier.

My terraform script work fine since many months but last days I needed to add more IP address (about 50). 
When terraform add IP to Atlas, some IP throwing an error after 21 retry. Howerver when I check in Atlas UI I see all IP has been added but terraform failed.

### Terraform CLI and Terraform MongoDB Atlas Provider Version
Terraform v0.15.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.9.1

### Terraform Configuration File 
No specific configuration

```hcl
# distinct_outbound_ips =>  List of 50 IP
#   ["yyy.50.2.xx",
#  "yyy.50.2.xx",
#  "yyy.61.224.xx"
#   ...]

output "outbound_ips" {
  value = local.distinct_outbound_ips
}

# Add Outbount Ip to Mongo Atlas
resource "mongodbatlas_project_ip_access_list" "applications_access_list" {
  for_each =  {
        for key, value in local.distinct_outbound_ips : key => value
  }
  project_id = var.mongodb_atlas.project_id
  ip_address = each.value
  comment    = format("Azure %s %s %s","azure", "prod", each.key)
}

```

> I also tried with `mongodbatlas_project_ip_whitelist` same result 

### Steps to Reproduce
1. Init
```
terraform init `
    -backend-config="subscription_id=$Env:ARM_SUBSCRIPTION_ID" `
    -backend-config="storage_account_name=$Env:ARM_STORAGE_ACCOUNT" `
    -backend-config="container_name=container-tfstate" `
    -backend-config="key=terraform" `
    -backend-config="tenant_id=$Env:ARM_TENANT_ID" `
    -backend-config="client_id=$Env:ARM_CLIENT_ID" `
    -backend-config="client_secret=$Env:ARM_CLIENT_SECRET" `
    -backend-config="resource_group_name=$Env:RESOURCE_GROUP"
```
2. `terraform workspace select prod`
3. `terraform apply -var-file="env/env.prod.tfvars"`

### Expected Behavior
All Ip address in list should be add to Atlas Access List with no error

### Actual Behavior
All IP has been added but terraform failed 

### Crash Output
```
mongodbatlas_project_ip_whitelist.applications_access_list["38"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["46"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["28"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["11"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["17"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["20"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["0"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["25"]: Creating...

.....

mongodbatlas_project_ip_whitelist.applications_access_list["0"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["38"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["11"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["46"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["25"]: Still creating... [3m20s elapsed]

 Error: error creating Project IP Whitelist information: couldn't find resource (21 retries)

   with mongodbatlas_project_ip_whitelist.applications_access_list["17"],
   on main.tf line 781, in resource "mongodbatlas_project_ip_whitelist" "applications_access_list":
  781: resource "mongodbatlas_project_ip_whitelist" "applications_access_list" {

```
> But IPs were added

**Comment by themantissa** [comment] 2021-06-03 21:03
@nikhil-mongo  would you have time to be able to repro this and file an internal ticket for us to investigate if required.  Thank you

**Comment by srenno** [comment] 2021-06-04 07:57
> @nikhil-mongo would you have time to be able to repro this and file an internal ticket for us to investigate if required. Thank you

Hi, 
I have done a little  terraform script in order to reproduce this issue.
[issue-atlas.zip](https://github.com/mongodb/terraform-provider-mongodbatlas/files/6596716/issue-atlas.zip)

You have just to put your atlas settings (cf : readme)

**Comment by nikhil-mongo** [comment] 2021-06-05 02:48
@srenno Thanks for your effort in sharing the zip for me to repro.
I did the repro and could successfully add the IP addresses without failure at both Atlas and Terraform end. Terraform completed successfully adding 50 IP addresses.

Is it a recurring issue for you? Or occurred once or twice due to some system/network issue? It would be better to share the below details if it reoccurs.

- export TF_LOG=TRACE
- export TF_LOG_PATH=trace.log (share this log file)

Thanks.

**Comment by srenno** [comment] 2021-06-07 08:09
Done, I removed/changed sensitive data in provided log.
[trace.log](https://github.com/mongodb/terraform-provider-mongodbatlas/files/6606999/trace.log)

I had no error when I have no IP in atlas whitelist, But when atlas whitelist (atlas UI console) grow I always have the problem.
> I tested on WSL ubuntu and I reproduced the problem too.

Can you test with more than 150 ip in your atlas whitelist (atlas UI console) ?
Thanks.

**Comment by srenno** [comment] 2021-06-16 09:06
Hi, 
I Launch the script with 50 IP on new Atlas project with no IP in Atlas Whitelist and I got no error too.
But on atlas with more than 100 IP in Whitelist, when I try to add the provided IP list I always reproduce the issue.

**Comment by nikhil-mongo** [comment] 2021-06-17 04:19
@srenno I shall update you with the details today and if we continue to reproduce it, I will file a ticket internally.

**Comment by nikhil-mongo** [comment] 2021-06-17 10:28
PRODTRIAGE-1786 filed internally.

**Comment by themantissa** [comment] 2021-09-02 20:52
Fixed in recent release 1.0.1

**Closed as completed by themantissa** 2021-09-02 20:52 UTC
Labels: bug

**Comment by SamBallantyne** [comment] 2022-03-06 23:24
👋 I'm seeing this in 1.3.0

**Comment by themantissa** [comment] 2022-03-08 00:52
@SamBallantyne as you can see from the issue this was corrected.  If you are again experiencing the issue you should open a new Issue.  Please include all the requested information in the issue template.  Not including that severely reduces our ability to help.
