### ISSUE TITLE
Cluster not renamed when the name changes

### ISSUE THREAD

**Issue by haidaraM** [mongodb/terraform-provider-mongodbatlas#189] opened 2020-04-08 14:30 UTC
Looks like the cluster is not renamed when we change its name. Terraform seems to successfully update the name but nothing changes in Atlas Console. 

The doc says that the `name` can't be changed after cluster creation (https://www.terraform.io/docs/providers/mongodbatlas/r/cluster.html#name). So I guess the cluster should be recreated when its name changes :-) ?

**Comment by themantissa** [comment] 2020-04-08 17:23
@haidaraM - correct, the UI supports changing the cluster name but the API does not.   Terraform considers the name change a change of cluster and will delete the old cluster and create with the new name so be cautious and aware of this behavior.

**Comment by haidaraM** [comment] 2020-04-08 17:30
The issue is that currently Terraform doesn't delete the old cluster. The cluster keeps it's old name even though I apply the change. Terraform plan says that the resource will be updated in place.
Is this the expected behavior  ?

**Comment by themantissa** [comment] 2020-04-08 17:33
Interesting - let me test it out again.

**Comment by themantissa** [comment] 2020-04-08 17:46
Ah, I skimmed this too quickly.   The behavior I was describing is for Atlas Projects (you can change the name in the UI, not via API and if you try to it will delete the project and recreate - there is a warning we put in the docs) but this is for Clusters!  Cluster names are special and cannot be changed so this is a bit of a bug in the Provider!  It should error when you try to change the name but it looks like it is applying, but since it cannot apply that is shouldn't try.   @haidaraM deleted my incorrect comment and noted this a non-blocking bug.  It doesn't impact anything but may lead to false impressions of what changed.

**Comment by andreykaipov** [comment] 2021-04-16 21:19
> It should error when you try to change the name but it looks like it is applying, but since it cannot apply that is shouldn't try.

@themantissa Maybe I'm misunderstanding this, but is the expected behavior to have the provider force a new cluster, or for the Atlas API to respond with a 400 such that that the provider errors out?

I tried to change our cluster names yesterday, and Terraform accepted the plan, so I'm guessing the Atlas API incorrectly accepts the request. However, the API doesn't really need to change to improve the provider. I think https://github.com/mongodb/terraform-provider-mongodbatlas/pull/435 accomplishes this.

**Comment by themantissa** [comment] 2021-04-19 23:50
@andreykaipov based on your PR I tested and the API actually correctly returned an error when a cluster name was submitted via PATCH so we can actually change the provider to capture that error correctly (not sure why before I said it shouldn't try, it can and then return the error.)  I'm putting a ticket in to improve this but will take a bit of time as we have quite a bit on our near term roadmap.

**Comment by andreykaipov** [comment] 2021-04-20 00:14
That's fine, thanks I appreciate it. We don't really plan on changing our cluster names any time soon anyways 😛 

I don't want to split the discussion between the issue and the PR, but regardless of whatever logic does the error propagation, I still believe Terraform should definitely show the correct plan. The provider shouldn't consider a name change as an in-place update, only to error out when actually applying the plan. That makes for very poor UX.

**Comment by themantissa** [comment] 2021-04-20 00:16
Agree, and we'll get it fixed.  I'll leave this issue open and close the PR for now.  Thank you  😄

**Comment by themantissa** [comment] 2021-04-20 00:18
Internal ticket INTMDB-201

**Comment by themantissa** [comment] 2022-02-24 00:38
Also reported in https://github.com/mongodb/terraform-provider-mongodbatlas/issues/676.  Seems we may still not be erroring correctly when someone tries to change a cluster name via the provider.

**Comment by themantissa** [comment] 2022-10-19 19:08
Haven't seen any more issues with this in 2 years so closing.

**Closed as completed by themantissa** 2022-10-19 19:08 UTC
Labels: non-blocking bug
