### ISSUE TITLE
breaking change in data.mongodbatlas_cluster.connection_strings on v1.12

### ISSUE THREAD

**Issue by mitre-tm** [mongodb/terraform-provider-mongodbatlas#1658] opened 2023-11-22 23:52 UTC
When only updating `mongodb/mongodbatlas` from [1.10.2](https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/v1.10.2) to [1.13.0](https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/v1.13.0) (latest as of the opening of this issue), the error appeared:
```
│ Error: Invalid index
│ 
│   on mongodb_atlas_database_triggers/privatelink.tf line 67, in locals:
│   67:   private_link_endpoint     = data.mongodbatlas_cluster.main.connection_strings[0].aws_private_link_srv[local.private_link_id]
│     ├────────────────
│     │ data.mongodbatlas_cluster.main.connection_strings[0].aws_private_link_srv is empty map of string
│     │ local.private_link_id is "vpce-0673c86eec54819ec"
│ 
│ The given key does not identify an element in this collection value.
```

The was no change to the Terraform code itself.

After some bisecting, I identified that the breaking change was introduced in [v1.12.0](https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/v1.12.0) and I am able to upgrading the provider up to [v1.11.1](https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/v1.11.1) without issues.

I glanced at the [diff](https://github.com/mongodb/terraform-provider-mongodbatlas/compare/v1.11.1...v1.12.0), but I could not promptly identify any clues by searching for "connection_strings".

> If you have an active MongoDB Atlas Support contract, the best way for us to assist you with the Terraform MongoDB Atlas Provider is through a [support ticket](https://support.mongodb.com/).

I will also open a ticket there, linking to this issue.

**Comment by marcosuma** [comment] 2023-11-23 06:57
Hi @mitre-tm, first of all thank you for using `terraform-provider-mongodbatlas` and raising this issue to us.

I wanted to kindly bring you to the attention that we currently don't follow a full `semantic versioning` approach. Our approach is currently more similar to `vBIG_MAJOR_CHANGE.MAJOR_CHANGE.MINOR_CHANGE` - this means that indeed upgrading from `v1.10.x` to `v.11.y` will **contain breaking changes**.

While I can tell you we are working on planning a change in the way we treat our versioning system, I am afraid we still don't have an exact timeline for that.

Said that, regarding your issue: in v1.12.0 we introduced major Terraform changes such as _migrated to [Plugin Protocol Version 6](https://developer.hashicorp.com/terraform/plugin/terraform-plugin-protocol#protocol-version-6)_. While this might not be the exact root cause, it will potentially be related.

As you might have seen when creating the issue, there was a list of information to put in order for us to assist with your issue. As that information is missing, I am afraid I cannot provide further details of what is the root cause since providing only the error is not enough.

I am going to close this issue, feel free to re-open by providing the full required information as per the issue template.
 
Thank you for your patience.

**Closed as completed by marcosuma** 2023-11-23 06:57 UTC

**Comment by mitre-tm** [comment] 2023-11-24 00:17
@marcosuma Thanks for the prompt response.

I am allowed to share futher details privately, but it seems that the breaking change was intended and, thus, there will be no debugging or fixing to benefit from it. The way I understand, it is on users to adapt. 

Would you be so kind to share a migration guide, then?

**Comment by marcosuma** [comment] 2023-11-24 05:32
Hi @mitre-tm, thanks for your understanding. We don't simply want to leave users to adapt, we're happy to assist on issues and, if it's the case, fix bugs or implement feature requests whenever needed.

What I meant to say in my previous message is simply that breaking changes between those version numbers are intended. 

It is also possible though that they might not have been documented as well which is a miss on our side. That's why I suggested you to provide us with all information needed and we'll be able to assist you. Please feel free to open a ticket or share this with us in any other way you suggest.
