### ISSUE TITLE
[Bug]: Federated Data Instances does not handle `dataProcessRegion`

### ISSUE THREAD

**Issue by sebastianhaeni** [mongodb/terraform-provider-mongodbatlas#2013] opened 2024-03-12 16:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

registry.terraform.io/mongodb/mongodbatlas v1.15.1

### Terraform Version

Terraform v1.7.4 on darwin_amd64

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

When setting `dataProcessRegion` on `mongodbatlas_federated_database_instance`, this error appears:

```
│ Error: error updating MongoDB Atlas Federated Database Instace (engineering): https://cloud.mongodb.com/api/atlas/v2/groups/xxx/dataFederation/xxx PATCH: HTTP 400 Bad Request (Error code: "INVALID_JSON_ATTRIBUTE") Detail: Received JSON for the dataProcessRegion attribute does not match expected format. Reason: Bad Request. Params: [dataProcessRegion]
```

Probably relates to https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1634

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_federated_database_instance" "federated-data-analytics" {
  project_id = "1234"
  name       = "test"
  data_process_region {
    cloud_provider = "AWS"
    region         = "EU_WEST_1"
  }
}
```

### Steps To Reproduce

Either apply the Terraform resource.

Or set the `dataProcessRegion` on Atlas and then try to update that resource.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AgustinBettati** [comment] 2024-03-15 09:59
Hello @sebastianhaeni! 

I was able to reproduce your issue and identified that it is due to an incorrect value in `data_process_region.region`. By using the following adjusted configuration I was able to obtain a successful creation:

```
resource "mongodbatlas_federated_database_instance" "federated-data-analytics" {
  project_id = var.project_id
  name       = "test-oregon"
  data_process_region {
    cloud_provider = "AWS"
    region         = "OREGON_USA"
  }
}
```

As mentioned in our docs https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/federated_database_instance#region you can look into the supported values for the region attribute.

We will keep this ticket open so we can address gaps in our existing documentation and examples for the `data_process_region` attribute. Additional we will look into improving the error message so that it is more clear that the error is due to an incorrect value in the region.

**Comment by sebastianhaeni** [comment] 2024-03-15 10:55
That was indeed the problem. I checked the value the API returns on the Atlas Web UI and it was `EU_WEST_1`. I guess that was unrelated.

**Comment by lantoli** [comment] 2024-05-03 07:45
hi @sebastianhaeni , the PR has already been merged, and the fix will be available in the next release

**Closed as completed by lantoli** 2024-05-03 07:45 UTC
