### ISSUE TITLE
resource mongodbatlas_auditing audit_filter param doesn't ignore whitespace changes in json

### ISSUE THREAD

**Issue by timmobbs** [mongodb/terraform-provider-mongodbatlas#477] opened 2021-06-18 05:26 UTC
```hcl
Terraform v0.13.7
+ provider registry.terraform.io/mongodb/mongodbatlas v0.9.1

Your version of Terraform is out of date! The latest version
is 1.0.0. You can update by downloading from https://www.terraform.io/downloads.html
```
Note: I also tested this on Terraform 1.0 with the same result

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "this" {
  name   = "my_test"
  org_id = "<orgid here>"

}

resource "mongodbatlas_auditing" "audit" {
  project_id                  = mongodbatlas_project.this.id
  audit_filter                = file("./test.json")
  audit_authorization_success = false
  enabled                     = true
}
```

```json
{ "atype": "authenticate", "param": {   "user": "auditAdmin",   "db": "admin",   "mechanism": "SCRAM-SHA-1" }}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform apply`

### Expected Behavior
Apply the same json config from a file for the audit_filter shouldn't result in a change

### Actual Behavior
Provider always updates the audit_filter due to whitespace changes.
Note: The code sample provided in the documentation works fine where the json is inputed directly as a string. The issue occurs if json is from a file, a template file, or a heredoc.

### Debug Output 
```
2021-06-17T17:43:32.044-0700 [WARN]  Provider "registry.terraform.io/mongodb/mongodbatlas" produced an unexpected new value for mongodbatlas_auditing.audit during refresh.
      - .audit_filter: was cty.StringVal("{ \"atype\": \"authenticate\", \"param\": {   \"user\": \"auditAdmin\",   \"db\": \"admin\",   \"mechanism\": \"SCRAM-SHA-1\" }}\n"), but now cty.StringVal("{ \"atype\": \"authenticate\", \"param\": {   \"user\": \"auditAdmin\",   \"db\": \"admin\",   \"mechanism\": \"SCRAM-SHA-1\" }}")
```

### Crash Output
N/A

### Additional Context
No

### References
Here is a similar issue that was fixed on the AWS provider
https://github.com/hashicorp/terraform/pull/12380/files

**Comment by themantissa** [comment] 2021-06-21 22:45
Thank you for the report @timmobbs.  Let us take a look and report back.

**Comment by nikhil-mongo** [comment] 2021-06-23 04:54
Hi @timmobbs 

I am able to add the audit.json for the first time and then nothing happens next time onwards when I run **terraform apply**.

I used both, using the filer directly and then passing through the file. There is no issue in any of the approach. But if you are facing it please share the below details with us.

Run the below command -

```
- export TF_LOG=TRACE
- export TF_LOG_PATH=trace.log
- terraform init
- terraform apply
- terraform apply
```
Share the trace.log with us here and we can see what is happening at your end.

Thanks.

**Comment by themantissa** [comment] 2021-06-28 17:03
Since we have been unable to reproduce closing the issue.   If you'd like to provide the requested data above we'll be happy to take a look.

**Closed as completed by themantissa** 2021-06-28 17:03 UTC

**Comment by timmobbs** [comment] 2021-06-30 22:39
So the issue is just with a newline at the end of the json file.  I've updated my editor config to strip it off and that will suffice for my needs.

**Comment by themantissa** [comment] 2021-06-30 22:56
Thank you for letting us know @timmobbs.  Nicely tracked down!
