### ISSUE TITLE
accepter_region_name not required for AWS on read/import/update

### ISSUE THREAD

**Issue by edahlseng** [mongodb/terraform-provider-mongodbatlas#53] opened 2019-10-24 21:24 UTC
According the [documentation](https://www.terraform.io/docs/providers/mongodbatlas/r/network_peering.html#accepter_region_name), the `accepter_region_name` is required for resource `mongodbatlas_network_peering`. Nevertheless, when we first imported our resources (migrating from the original third-party provider), we didn't encounter an error when we left out `accepter_region_name`.

Checking [mongodbatlas/resource-mongodbatlas_network_container.go](https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/e651f1caf9ad304d3048d0d78c45995c167c21cb/mongodbatlas/resource_mongodbatlas_network_container.go), it appears that this constraint is _only_ enforced upon create. While this is a bit of an edge case, it might be worth enforcing this constraint across all operations for consistency.

**Comment by themantissa** [comment] 2019-11-01 20:33
@edahlseng thank you.  We'll add this as a non-blocking bug.  Thank you.

**Comment by mpaluchowski** [comment] 2020-03-09 13:35
This is causing problems for us now, because we also originally created `mongodbatlas_network_peering` resources without the `accepter_region_name`. Last week we added a new cluster, where we had to add `accepter_region_name` to the resource. Because we're using a shared module for all our clusters, Terraform now wants to update the previously created network peerings, adding the region name. This operation fails with:

```
Error: error updating MongoDB Network Peering Connection (<id>): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/<id>/peers/<id>: 409 (request "Conflict") The peer with ID <id>in group <id> cannot be updated in its current state.
```

**Comment by themantissa** [comment] 2020-03-09 17:12
Acknowledged and will note in backlog priority.

**Comment by gmlp** [comment] 2020-06-12 19:02
Hi @edahlseng, I can't reproduce this issue. can you try to reproduce this issue with the latest provider version, we have made some changes to the code.

**Comment by themantissa** [comment] 2020-06-16 21:00
@mpaluchowski and @edahlseng - we are having issues reproducing this.  Can you check with the latest version and let us know if you are still hitting it?

**Comment by mpaluchowski** [comment] 2020-06-17 04:41
I can check it out next week and let you know.

**Comment by themantissa** [comment] 2020-06-17 20:01
Thank you @mpaluchowski - very much appreciate your frequent help and reporting on these!

**Comment by mpaluchowski** [comment] 2020-06-24 19:55
@themantissa I just checked and we still have the same issue. For the clusters created early, before `accepter_region_name` became mandatory, `terraform plan` still wants to add this value:

```
  ~ resource "mongodbatlas_network_peering" "default" {
      + accepter_region_name   = "eu-west-3"
      ...
    }
```

and when I run `terraform apply` with this plan, I get:

```
Error: error updating MongoDB Network Peering Connection (<id>): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/<id>/peers/<id>: 409 (request "Conflict") The peer with ID <id> in group <id> cannot be updated in its current state.
```

I have to keep this entry in our peering resource block:

```
  lifecycle {
    ignore_changes = [accepter_region_name]
  }
```

**Comment by themantissa** [comment] 2020-06-24 20:09
Thank you @mpaluchowski !

**Comment by PacoDw** [comment] 2020-07-06 19:15
Hello @mpaluchowski and @edahlseng ! 
Thank you so much for your review, I made changes on the same branch fixing the bug and added a test case to validate it, so could you test it to check if everything is okay plz?

Let me know if you have another concern or comment 👍

**Comment by themantissa** [comment] 2020-07-08 18:35
@mpaluchowski or @edahlseng any feedback on the proposed fix?  Looks good from our side but before releasing would be great to have a verification.

**Comment by mpaluchowski** [comment] 2020-07-09 19:47
Hmm, how do I test an unreleased version? Do I need to build it myself first?

**Comment by themantissa** [comment] 2020-07-09 19:51
Correct @mpaluchowski , you'd need to build from the branch the fix is in and ensure you have the correct golang version (for that it should be either 1.13 or 1.14  - I believe 1.14 will be best but @PacoDw can confirm - we are about to update the README w/ the next release).  It's a bit of work but helps us verify it fixes the specific issue.   If not we can release the assumed fix in 0.6.2 and if it does not correct it then try to schedule in time to re-address.

**Comment by PacoDw** [comment] 2020-07-09 20:36
Hello, @mpaluchowski you need to switch to the branch `fixes-53-accepter_region_name-not-required-for-aws` and make a git pull to get all the recent changes, and ensure that you are using the go version > 1.13 if you have v1.14 it's excellent, make a `go build` later move the binary to your project folder, make `terraform init` and run your Terraform configuration.

**Closed as completed** 2020-07-13 22:30 UTC
Labels: bug

**Comment by mpaluchowski** [comment] 2020-07-14 10:55
Sorry I didn't make it. Too much to do lately and I currently don't even have Go installed. I'll wait for you to release the next version and then see if the error is gone.
